### ISSUE TITLE
Twitter invite does not worked.

### ISSUE THREAD

**Issue by Masabow** [appsocially/AppSocially-iOS-SDK#5]
I sent an Invite on Twitter Use the FirstSampleDemo but DM is not sent. 
Transmission history remains in the Dashboard. 

I was try "Face book" it is worked.
I have forgotten to set something?

**Comment by aerodynamics** [comment]
Hi Masabow,

Thanks for using AppSocially. 

Regarding Twitter, it looks like there's problem for sending URLs on DM. It is caused by Twitter Platform. Sorry about this. We are keeping our eyes on it and will update you as soon as we know their updates.
http://techcrunch.com/2013/10/16/twitter-says-a-technical-issue-is-preventing-urls-from-being-sent-in-direct-messages-for-some/

**Comment by Masabow** [comment]
I did understand this problem.
But we will use this awesome SDK!
We hope twitter's backend update.

Thank you for your reply.

**Comment by aerodynamics** [comment]
Awesome. Thanks again using AppSocially.

**Comment by matiasf9** [comment]
Did you solve this issue??

**Comment by aerodynamics** [comment]
@matiasf9, No. Sorry we can't so far, because it's the problem of the platform.
